name: polygon_clipper
description: A plugin to clip a Widget into a polygon shape. Works with any kind of Widget.
version: 1.0.1
author: Leonardo Caldas <leonardo.ferreira.caldas@gmail.com>
homepage: https://github.com/leonardocaldas/flutter-polygon-clipper

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"